import { jsPDF } from 'jspdf';
import { TranslationJob, TranslationPage } from '../types';

export interface ExportPdfOptions {
  fontSize?: 'small' | 'medium' | 'large';
  pageSize?: 'A4' | 'Letter';
}

/**
 * Generates an elegant, publication-quality Sinhala PDF book using high-DPI canvas
 * layout engine with native Noto Sans Sinhala glyph shaping, preventing corrupt/tofu boxes.
 */
export async function exportSinhalaPdf(
  job: TranslationJob,
  pages: TranslationPage[],
  options: ExportPdfOptions = {}
): Promise<Blob> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidthMm = 210;
  const pageHeightMm = 297;
  const marginMm = 20;
  const printableWidthMm = pageWidthMm - marginMm * 2;
  const printableHeightMm = pageHeightMm - marginMm * 2;

  // Render Title Page
  const titleCanvas = document.createElement('canvas');
  // High DPI scaling (300 DPI equivalent)
  const scale = 2;
  const canvasWidth = 800 * scale;
  const canvasHeight = 1131 * scale; // 1:1.414 A4 ratio
  titleCanvas.width = canvasWidth;
  titleCanvas.height = canvasHeight;

  const ctx = titleCanvas.getContext('2d');
  if (ctx) {
    ctx.scale(scale, scale);
    renderTitlePage(ctx, 800, 1131, job);
    const titleImgData = titleCanvas.toDataURL('image/jpeg', 0.95);
    doc.addImage(titleImgData, 'JPEG', 0, 0, pageWidthMm, pageHeightMm);
  }

  // Filter completed or populated pages
  const validPages = pages
    .filter(p => p.translatedSinhala && p.translatedSinhala.trim().length > 0)
    .sort((a, b) => a.pageNumber - b.pageNumber);

  // If no pages translated yet, render empty notice
  if (validPages.length === 0) {
    doc.addPage();
    doc.setFontSize(14);
    doc.text('No translated pages available to export.', 20, 30);
    return doc.output('blob');
  }

  // Render each book page
  for (let i = 0; i < validPages.length; i++) {
    const pageData = validPages[i];
    doc.addPage();

    const pageCanvas = document.createElement('canvas');
    pageCanvas.width = canvasWidth;
    pageCanvas.height = canvasHeight;
    const pageCtx = pageCanvas.getContext('2d');

    if (pageCtx) {
      pageCtx.scale(scale, scale);
      renderBookPage(
        pageCtx, 
        800, 
        1131, 
        pageData.translatedSinhala, 
        pageData.pageNumber, 
        job.originalFileName.replace(/\.pdf$/i, ''),
        options.fontSize || 'medium'
      );
      const pageImgData = pageCanvas.toDataURL('image/jpeg', 0.95);
      doc.addImage(pageImgData, 'JPEG', 0, 0, pageWidthMm, pageHeightMm);
    }
  }

  return doc.output('blob');
}

function renderTitlePage(
  ctx: CanvasRenderingContext2D,
  width: number,
  height: number,
  job: TranslationJob
) {
  // Creamy book page background
  ctx.fillStyle = '#faf9f5';
  ctx.fillRect(0, 0, width, height);

  // Outer border frame
  ctx.strokeStyle = '#d4af37';
  ctx.lineWidth = 2;
  ctx.strokeRect(40, 40, width - 80, height - 80);

  ctx.strokeStyle = '#2c2a29';
  ctx.lineWidth = 1;
  ctx.strokeRect(46, 46, width - 92, height - 92);

  // Header ornamentation
  ctx.fillStyle = '#7a6e5d';
  ctx.font = '600 14px "Plus Jakarta Sans", sans-serif';
  ctx.textAlign = 'center';
  ctx.letterSpacing = '3px';
  ctx.fillText('SINHALA LITERARY TRANSLATION EDITION', width / 2, 140);

  // Main Book Title
  ctx.fillStyle = '#1a1918';
  ctx.font = 'bold 34px "Plus Jakarta Sans", "Noto Sans Sinhala", serif';
  ctx.letterSpacing = '0px';
  
  const cleanTitle = job.originalFileName.replace(/\.pdf$/i, '');
  wrapAndFillText(ctx, cleanTitle, width / 2, 280, width - 180, 44, 'center');

  // Sinhala Subtitle
  ctx.fillStyle = '#b36b00';
  ctx.font = 'bold 24px "Noto Sans Sinhala", sans-serif';
  ctx.fillText('සිංහල පරිවර්තනය', width / 2, 390);

  // Divider line
  ctx.strokeStyle = '#d4af37';
  ctx.lineWidth = 1.5;
  ctx.beginPath();
  ctx.moveTo(width / 2 - 80, 430);
  ctx.lineTo(width / 2 + 80, 430);
  ctx.stroke();

  // Genre badge
  ctx.fillStyle = '#4a4846';
  ctx.font = 'italic 16px "Plus Jakarta Sans", sans-serif';
  ctx.fillText(`Category: ${job.genre.toUpperCase()}`, width / 2, 500);

  // Footer metadata
  ctx.fillStyle = '#6e6962';
  ctx.font = '13px "Noto Sans Sinhala", sans-serif';
  ctx.fillText('Google Gemini AI මගින් ස්වභාවික සිංහල භාෂාවට පරිවර්තනය කරන ලදී', width / 2, height - 120);
  ctx.font = '12px "Plus Jakarta Sans", sans-serif';
  ctx.fillText(`Generated by SinhalaBook Translator • Total Pages: ${job.totalPages}`, width / 2, height - 96);
}

function renderBookPage(
  ctx: CanvasRenderingContext2D,
  width: number,
  height: number,
  sinhalaContent: string,
  pageNumber: number,
  bookTitle: string,
  fontSizeOption: 'small' | 'medium' | 'large'
) {
  // Page background
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, width, height);

  // Running Header
  ctx.fillStyle = '#8c827a';
  ctx.font = '11px "Plus Jakarta Sans", sans-serif';
  ctx.textAlign = 'left';
  ctx.fillText(truncateString(bookTitle, 45), 60, 45);

  ctx.textAlign = 'right';
  ctx.fillText('සිංහල පරිවර්තනය', width - 60, 45);

  // Thin header rule
  ctx.strokeStyle = '#e6e1d8';
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(60, 54);
  ctx.lineTo(width - 60, 54);
  ctx.stroke();

  // Running Footer / Page Number
  ctx.textAlign = 'center';
  ctx.fillStyle = '#59534c';
  ctx.font = '12px "Plus Jakarta Sans", sans-serif';
  ctx.fillText(`— ${pageNumber} —`, width / 2, height - 40);

  // Body text configuration
  let bodyFontSize = 15;
  let lineHeight = 26;
  if (fontSizeOption === 'small') {
    bodyFontSize = 13;
    lineHeight = 22;
  } else if (fontSizeOption === 'large') {
    bodyFontSize = 17;
    lineHeight = 30;
  }

  const marginX = 65;
  const contentWidth = width - marginX * 2;
  let startY = 90;

  // Split paragraphs
  const paragraphs = sinhalaContent.split(/\n+/);

  ctx.textAlign = 'left';
  ctx.fillStyle = '#1c1b1a';

  for (const para of paragraphs) {
    if (!para.trim()) continue;

    // Check if paragraph looks like a Chapter / Section heading
    const isHeading = /^(පරිච්ඡේදය|Chapter|[0-9]+\s*වන\s*පරිච්ඡේදය|හැඳින්වීම|සාරාංශය)/i.test(para.trim()) || para.trim().length < 40;

    if (isHeading && para.trim().length < 60) {
      startY += 10;
      ctx.font = 'bold 20px "Noto Sans Sinhala", sans-serif';
      ctx.fillStyle = '#8f4f00';
      startY = wrapAndFillText(ctx, para.trim(), marginX, startY, contentWidth, 30, 'left');
      startY += 8;
      ctx.fillStyle = '#1c1b1a';
    } else {
      ctx.font = `${bodyFontSize}px "Noto Sans Sinhala", sans-serif`;
      startY = wrapAndFillText(ctx, para.trim(), marginX, startY, contentWidth, lineHeight, 'left');
      startY += lineHeight * 0.45; // paragraph spacing
    }

    if (startY > height - 80) {
      break; // prevent overflowing off-page
    }
  }
}

function wrapAndFillText(
  ctx: CanvasRenderingContext2D,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number,
  align: 'left' | 'center'
): number {
  const words = text.split(/\s+/);
  let currentLine = '';
  let curY = y;

  for (let n = 0; n < words.length; n++) {
    const testLine = currentLine + (currentLine ? ' ' : '') + words[n];
    const metrics = ctx.measureText(testLine);
    const testWidth = metrics.width;

    if (testWidth > maxWidth && n > 0) {
      ctx.fillText(currentLine, x, curY);
      currentLine = words[n];
      curY += lineHeight;
    } else {
      currentLine = testLine;
    }
  }

  if (currentLine) {
    ctx.fillText(currentLine, x, curY);
    curY += lineHeight;
  }

  return curY;
}

function truncateString(str: string, maxLen: number): string {
  if (str.length <= maxLen) return str;
  return str.substring(0, maxLen - 3) + '...';
}
